(ns glurps.process.db.properties)

(def binary :binary)
(def boolean :boolean)
(def byte :byte)
(def embedded :embedded)
(def embeddedlist :embeddedlist)
(def embeddedmap :embeddedmap)
(def embeddedset :embeddedset)
(def decimal :decimal)
(def float :float)
(def date :date)
(def datetime :datetime)
(def double :double)
(def integer :integer)
(def link :link)
(def linklist :linklist)
(def linkmap :linkmap)
(def linkset :linkset)
(def long :long)
(def short :short)
(def string :string)
